# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35acb2a6dd16a268bbdd4a351d5e9ca875f9096b798c5a6da287a1e78c863ff1abff70e619ecd2357ba153f68e2eef5598cc4c7dfef32acdd515d3c207a366df

test:
  secret_key_base: 1da1f60770fd03c9c1a3ef25fae779a7a54f57a620ab35990cc505c70e35665cdf9e85d7f60bb4c9ac4fe7542c633f526a5aa5178c15befab9d7fbea9ce3c23c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
